### ISSUE TITLE
API documentation for OBIS?

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rOBIS#3]
Is there a documented API for OBIS? We were looking at it as a possible addition to the EcoData Retriever, but we haven't been able to find any description of how we might access the data outside of the web form/map system. It seems like you've figured it out so I was wondering if you could point me in the right direction. Thanks.

**Comment by karthik** [comment]
Unfortunately there isn't, yet. emailing you now.

**Comment by ethanwhite** [comment]
Thanks. Closing.
